### ISSUE TITLE
HowTo Install, Sync & basic API calls

### ISSUE THREAD

**Issue by zicmama** [duniter-gchange/gchange-pod#9]
Does anyone knows a place to find documentation on install, synchronise and use one gchange-pod?
thanks

**Comment by blavenie** [comment]
To install : 
- get standalone ZIP from : https://github.com/duniter-gchange/gchange-pod/releases
- Follow this install doc, in Cesium+ Pod web site : 
  * https://github.com/duniter/cesium-plus-pod/blob/master/src/site/markdown/install.md
  * or (should be a copy) : http://doc.e-is.pro/cesium-plus-pod/install.html

- Read and edit the config file, at `config/elasticsearch.yml`

**Comment by blavenie** [comment]
I had this link into the README.md : 
https://github.com/duniter-gchange/gchange-pod/blob/master/README.md
